### ISSUE TITLE
Horse location collision?

### ISSUE THREAD

**Issue by jesdynf** [Hobbes0927/hec-wildhorses#1]
Hi,

I'm not a Lua programmer, so sorry to disturb you if I'm wrong, but are you sure this is correct and functional?

https://github.com/Hobbes0927/hec-wildhorses/blob/b7752ae3abd092d6a1c5214a0159d4243725b645/config.lua#L40

It seems to me that you're expecting a table of locations but you're just redefining the same `coords` key three times here, and I can't make this give me three pairs when I test in a REPL.

Thanks!

**Comment by Hobbes0927** [comment]
Hi.  Those are three-dimensional coordinate arrays for REDM/FIVEM and each value set represents the x, y, and z coordinates on the game map.  In this case, 40-42 represent three locations on the map that can be spawn points for the horses.  I don't think this will work in a REPL since this code is dependent upon RDR2 and REDM

**Comment by jesdynf** [comment]
Yeah, the link I tried to refer to it with is terrible. Here's the problem.

        locations = {
            coords = vector3(-5931.86, -3014.2, -1.99),
            coords = vector3(-5126.08, -2744.38, -8.08),
            coords = vector3(-4204.92, -2562.65, 8.44),
        },

I tried getting `x = { y = "a", y = "b" } ` to work in a REPL and it just wouldn't see both assignments, I'm pretty sure you want `locations = { vector3(...), vector3(...) }` there.

**Comment by Hobbes0927** [comment]
I see what you're saying now and someone else pointed it out too

**Comment by Hobbes0927** [comment]
Config file change fixed
